# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rack-linkify"
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wyatt Greene"]
  s.date = "2013-10-25"
  s.description = "\n      Any URLs that occur in the text of the web page are automatically surrounded\n      by an anchor tag.\n    "
  s.email = "techiferous@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
    "LICENSE",
    "Rakefile",
    "lib/rack-linkify.rb",
    "test/rackapp/app.rb",
    "test/rackapp/config.ru",
    "test/test_helper.rb",
    "test/twitter_links_test.rb",
    "test/urls_test.rb"
  ]
  s.homepage = "http://github.com/techiferous/rack-linkify"
  s.require_paths = ["lib"]
  s.requirements = ["none"]
  s.rubygems_version = "2.0.3"
  s.summary = "Rack middleware that adds anchor tags to URLs in text."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack-plastic>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<rack-plastic>, [">= 0.1.1"])
      s.add_development_dependency(%q<redgreen>, [">= 0"])
    else
      s.add_dependency(%q<rack-plastic>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rack-plastic>, [">= 0.1.1"])
      s.add_dependency(%q<redgreen>, [">= 0"])
    end
  else
    s.add_dependency(%q<rack-plastic>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rack-plastic>, [">= 0.1.1"])
    s.add_dependency(%q<redgreen>, [">= 0"])
  end
end

